#!/usr/bin/env bash
# ==================================================================================================
# Script Name: optimize-kernel.sh
# Description: Optimizes Linux kernel parameters for high-performance Redis deployments.
#              Configures network, TCP, memory, and file descriptor settings.
#
# Usage:       sudo ./scripts/optimize-kernel.sh
#
# Prerequisites:
#              - Root/sudo access
#              - Linux OS (tested on Ubuntu 24.04, Amazon Linux 2023)
#
# Author:      RedisForge Team
# License:     MIT
# ==================================================================================================

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root (use sudo)"
   exit 1
fi

SYSCTL_CONF="/etc/sysctl.d/99-redisforge.conf"
BACKUP_CONF="/etc/sysctl.d/99-redisforge.conf.backup.$(date +%Y%m%d_%H%M%S)"

log_info "RedisForge Kernel Optimization Script"
log_info "======================================"

# Backup existing configuration if it exists
if [[ -f "$SYSCTL_CONF" ]]; then
    log_warn "Backing up existing configuration to $BACKUP_CONF"
    cp "$SYSCTL_CONF" "$BACKUP_CONF"
fi

log_info "Creating optimized kernel configuration..."

cat > "$SYSCTL_CONF" << 'EOF'
# ==================================================================================================
# RedisForge Kernel Optimization
# Generated by optimize-kernel.sh
# ==================================================================================================

# ----------------------------------------------------------------------------
# Network Performance
# ----------------------------------------------------------------------------

# Maximum number of connection requests that can be queued
net.core.somaxconn = 65535

# Maximum number of packets in the receive queue
net.core.netdev_max_backlog = 5000

# Maximum TCP SYN backlog
net.ipv4.tcp_max_syn_backlog = 8192

# TCP receive and send buffer sizes (min, default, max in bytes)
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# Core socket receive and send buffer sizes
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 262144
net.core.wmem_default = 262144

# ----------------------------------------------------------------------------
# TCP Optimization
# ----------------------------------------------------------------------------

# Reduce TIME_WAIT sockets (useful for high-connection workloads)
net.ipv4.tcp_fin_timeout = 30

# TCP keepalive settings
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# Enable TCP Fast Open (reduces latency for repeat connections)
net.ipv4.tcp_fastopen = 3

# TCP window scaling
net.ipv4.tcp_window_scaling = 1

# Enable selective acknowledgments
net.ipv4.tcp_sack = 1

# Disable TCP slow start after idle
net.ipv4.tcp_slow_start_after_idle = 0

# ----------------------------------------------------------------------------
# Ephemeral Port Range
# ----------------------------------------------------------------------------

# Expand port range for high connection counts
net.ipv4.ip_local_port_range = 10000 65535

# ----------------------------------------------------------------------------
# File Descriptors
# ----------------------------------------------------------------------------

# Maximum number of file descriptors
fs.file-max = 1000000

# ----------------------------------------------------------------------------
# Virtual Memory
# ----------------------------------------------------------------------------

# Allow Redis to allocate memory beyond physical RAM (required for fork)
vm.overcommit_memory = 1

# Reduce swappiness (prefer RAM over swap)
vm.swappiness = 1

# Increase dirty page background writeback threshold
vm.dirty_background_ratio = 5
vm.dirty_ratio = 10

# ----------------------------------------------------------------------------
# Connection Tracking (for high connection counts)
# ----------------------------------------------------------------------------

# Maximum number of connection tracking entries
net.netfilter.nf_conntrack_max = 1048576

# Connection tracking timeout for established connections (seconds)
net.netfilter.nf_conntrack_tcp_timeout_established = 86400

# ----------------------------------------------------------------------------
# Security (DoS Protection)
# ----------------------------------------------------------------------------

# SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

EOF

log_info "Configuration written to $SYSCTL_CONF"

# Apply the configuration
log_info "Applying kernel parameters..."
if sysctl -p "$SYSCTL_CONF"; then
    log_info "✓ Kernel parameters applied successfully"
else
    log_error "Failed to apply kernel parameters"
    exit 1
fi

# Disable Transparent Huge Pages (THP) - improves Redis performance
log_info "Disabling Transparent Huge Pages (THP)..."

THP_ENABLED="/sys/kernel/mm/transparent_hugepage/enabled"
THP_DEFRAG="/sys/kernel/mm/transparent_hugepage/defrag"

if [[ -f "$THP_ENABLED" ]]; then
    echo never > "$THP_ENABLED"
    log_info "✓ THP disabled (enabled)"
else
    log_warn "THP enabled file not found (may already be disabled)"
fi

if [[ -f "$THP_DEFRAG" ]]; then
    echo never > "$THP_DEFRAG"
    log_info "✓ THP disabled (defrag)"
else
    log_warn "THP defrag file not found (may already be disabled)"
fi

# Make THP disable persistent across reboots
SYSTEMD_THP_SERVICE="/etc/systemd/system/disable-thp.service"

log_info "Creating systemd service to disable THP on boot..."

cat > "$SYSTEMD_THP_SERVICE" << 'EOF'
[Unit]
Description=Disable Transparent Huge Pages (THP)
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=redis.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'

[Install]
WantedBy=basic.target
EOF

systemctl daemon-reload
systemctl enable disable-thp.service
log_info "✓ THP disable service created and enabled"

# Configure file descriptor limits
log_info "Configuring file descriptor limits..."

LIMITS_CONF="/etc/security/limits.d/99-redisforge.conf"

cat > "$LIMITS_CONF" << 'EOF'
# RedisForge file descriptor limits
redis soft nofile 65536
redis hard nofile 65536
envoy soft nofile 65536
envoy hard nofile 65536
* soft nofile 65536
* hard nofile 65536
EOF

log_info "✓ File descriptor limits configured in $LIMITS_CONF"

# Summary
log_info ""
log_info "======================================"
log_info "Kernel Optimization Complete!"
log_info "======================================"
log_info ""
log_info "Applied optimizations:"
log_info "  ✓ Network performance (somaxconn, tcp buffers)"
log_info "  ✓ TCP optimization (keepalive, fast open)"
log_info "  ✓ Ephemeral port range expanded"
log_info "  ✓ File descriptor limits increased"
log_info "  ✓ Virtual memory overcommit enabled"
log_info "  ✓ Transparent Huge Pages disabled"
log_info "  ✓ Connection tracking optimized"
log_info ""
log_warn "IMPORTANT: Some changes require a reboot to take full effect."
log_info ""
log_info "Verify current settings:"
log_info "  sysctl -a | grep -E 'somaxconn|tcp_max_syn_backlog|overcommit_memory'"
log_info "  cat /sys/kernel/mm/transparent_hugepage/enabled"
log_info "  ulimit -n"
log_info ""
log_info "To revert changes, restore from: $BACKUP_CONF"
